//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalasDeReuniones
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sala()
        {
            this.estadoSalas = new HashSet<estadoSala>();
            this.reservas = new HashSet<reserva>();
            this.equipo_salas1 = new HashSet<equipo_salas>();
        }
    
        public int IdSala { get; set; }
        public string nombre { get; set; }
        public Nullable<int> capacidad { get; set; }
        public string ubicacion { get; set; }
        public string equipo_disponible { get; set; }
        public Nullable<System.TimeSpan> hora_inicio_dispo { get; set; }
        public Nullable<System.TimeSpan> hora_fin_dispo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estadoSala> estadoSalas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reservas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipo_salas> equipo_salas1 { get; set; }
        public List<string> Equipos { get; set; }
    }
}
