//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalasDeReuniones
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using Microsoft.AspNetCore.Identity;


    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.reservas = new HashSet<reserva>();
        }
    
        public int IdUsuario { get; set; }
        public Nullable<int> IdRol { get; set; }
        public string Usuario1 { get; set; }
        public string contrasena { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva> reservas { get; set; }
        [DisplayName("Rol del Usuario")]


        public virtual role role { get; set; }
        public void SetPassword(string password)
        {
            var hasher = new PasswordHasher<usuario>(); 
            this.contrasena = hasher.HashPassword(this, password); 
        }
    }
}
